### ISSUE TITLE
error with dump-pg.sh: line 77 work/imposm-0.10.0-linux-x86-64/imposm: cannot execute binary file

### ISSUE THREAD

**Issue by osama001** [geosolutions-it/osm-styles#16]
Hi

after I run this code 
`sudo ./dump-pg.sh -i /Users/osama_al-harbi/Desktop/go/gcc-states-latest.osm.pbf`

I got this error 

```
./dump-pg.sh: line 41: [: too many arguments
---------- Using user id 501 and username osama_al-harbi

----------- Starting up PostGIS docker image osm-postgis
a6a27be6fc03bf10481b9b0c8ba018b1a813a435a4c485c873ac6f71e44f3266

----------- Downloading and unpacking Imposm 3
Done

----------- Waiting for PostgreSQL to be up and running
Waiting for PostgreSQL, 29 remaining attempts...
Waiting for PostgreSQL, 28 remaining attempts...

----------- Running imposm, read from pbf
./dump-pg.sh: line 77: work/imposm-0.10.0-linux-x86-64/imposm: cannot execute binary file 
```

is there any idea what is the problem

I am using MAC OS

thnx

**Comment by aaime** [comment]
imposm binaries are available only for Linux. I believe you'll have to build it manually.
Never tried personally, I don't own a OSX machine (no one does in GeoSolutions).

Anyhow, not a specific issue to this data directory, you should check with the imposm people.
If you figure it out, would be nice to know what needs to be done so that we can add instructions in this repo?
