### ISSUE TITLE
Seeking Guidance on Configuring GeoServer for OSM-Style Data Styling

### ISSUE THREAD

**Issue by pmeems** [geosolutions-it/osm-styles#34]
Can you provide information on the current status of this project? While it appears promising, issue #31 highlights the unavailability of the Docker image. I've already established GeoServer and PostGIS containers, successfully imported OSM-Europe through osm2psql, and now seek guidance on styling my data akin to openstreetmap.org.

However, I'm encountering challenges in configuring GeoServer, establishing stores, and applying styles to achieve the desired OSM styles. Additionally, the usage of the `Pregeneralized Features` plugin, as recommended in the readme, remains unclear despite installation.

I would greatly appreciate insights or guidance from anyone who has successfully implemented this setup.

**Comment by aaime** [comment]
We should remove the docker image mentioned from the readme, it's not part of the project goals (this is just a GeoServer data directory). The README otherwise provides step by step instructions, including using imposm, and not osm2psql, to import the data. The database layouts and table you'll get out of the two tools are completely different, this data directory won't work with the osm2psql output.

**Comment by pmeems** [comment]
Thanks for your quick reply.
I will try imposm now.

But that will just fill my database. I assume I need to do something with the files in this repo, right?
I can just copy these files to my GeoServer data folder and then it works?

**Comment by pmeems** [comment]
Just to let you know I managed to get it all working.
I had to copy all files in this repo to my geoserver_data folder.
